# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  #config.vm.synced_folder '.', '/vagrant', type: 'nfs'
  config.vm.synced_folder "./files/", "/vagrant", mount_options: ["dmode=700,fmode=600"]

  # VirtualBox.
  config.vm.define "virtualbox" do |virtualbox|
    virtualbox.vm.hostname = "virtualbox-centos6"
    #virtualbox.vm.box = "file://builds/virtualbox-centos6.box"
    virtualbox.vm.box = "bento/centos-6"
    virtualbox.vm.network :private_network, ip: "172.16.3.88"

    config.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.provision :shell, path: "install-rvm.sh",  args: "stable", privileged: false # changed
    config.vm.provision :shell, path: "install-ruby.sh", args: "2.1.1",  privileged: false # changed
    $script = <<-SCRIPT
    yum install -y git
    SCRIPT

    config.vm.provision "shell", inline: $script
  end
end
